
--CREAR CARATULA DE DOCTO_PV, INICIALMENTE UNA VENTA
SELECT R_DOCTO_PV_ID, R_FOLIO
FROM CARATULA_DOCTOS_PV_FYTTSAGO(:branchId, :storageId, :clientCode, :clientId, :cashId, :type);
 "branchid es idsucursal, storageid es idalmacen, clientcode es CLAVE_CLIENTE, clientid es idcliente, cashid es idcaja y type es tipo de documento (V para venta, O para ORDEN, SOLO USARE V, etc)"
--INSERTAR DETALLES POR CADA ARTICULO/PARTIDA
SELECT R_SOLICITUD_TRASPASO_IN_ID, R_UNIDADES_FALTANTES, R_DOCTO_PV_ID_ORDEN, R_FOLIO_ORDEN
FROM INS_DOCTOS_PV_DET_FYTTSAGO(:documentId, :articleCode, :articleId, :units, :price, :requestId);
 "IDDOCUMENT ES LA GENERADA X EL PROCEDIMIENTO ANTERIOR (AL IGUAL Q EL FOLIO)"
--CALCULA LOS TOTALES
SELECT DOCTO_PV_ID, NUM_RENGLONES, NUM_ARTICULOS, SUBTOTAL, IMPORTE_NETO, TOTAL_A_PAGAR, TOTAL_RETENCIONES, PESO_TOTAL
FROM CALC_TOTALES_DOCTO_PV(:documentId, 'N', 'N', NULL);
 "TOTALES SE CALCULAN Y ACTUALIZAN AL PRIMER PROCEDIMIENTO (EN CARATULA) NECESARIO TOTAL_A_PAGAR PARA EL ULTIMO PROCEDIMIENTO DE COBROS, SI HAY RETENCIONES SE ACTUALIZAN EN LA CARATULA, PESO TOTAL SE CALCULA CON LOS ARTICULOS Y SE ACTUALIZA EN LA CARATULA"
--SE APLICA EL DOCUMENTO
EXECUTE PROCEDURE APLICA_DOCTO_PV(:documentId);
 "PASAR EL ID DEL DOCUMENTO GENERADO AL INICIO, LA CARATULA, PARA AFECTAR INVENTARIOS, CUENTAS POR COBRAR, ETC"
--INSERTAMOS LOS COBROS
EXECUTE PROCEDURE INS_DOCTO_PV_COBROS_FYTTSAGO(:documentId, :paymentId, :total, :reference, :bank, :cardNums, :date);
"ID DE DOCUMENTO, ID DE PAGO TABLA FORMAS_COBRO, TOTAL DE ARRIBA, FECHA ES STRING FECHA SOLO ES CUANDO ES TRANSFERENCIA  REFERENCIA EN TARJETAS ES NUMERO DE AUTORIZACION"