CREATE OR ALTER PROCEDURE CARATULA_DOCTOS_PV_FYTTSAGO(P_SUCURSAL_ID INTEGER, P_ALMACEN_ID INTEGER, P_CLAVE_CLIENTE VARCHAR(20), P_CLIENTE_ID INTEGER, P_CAJA_ID INTEGER, P_TIPO_DOCTO CHAR(1))
RETURNS (
	R_DOCTO_PV_ID INTEGER,
	R_FOLIO CHAR(9)
)
AS
/*
	Procedimiento Almacenado creado para FYTTSAGO, al ser específico para el E-COMMERCE, se tomaran ciertas decisiones que serán comentadas
	Parámetros de entrada:
	-P_SUCURSAL_ID: Solo se aceptaran las siguientes sucursales: Totolcingo, Tepexpan, Texcoco, Vallejo y Vía Morelos.
	-P_ALMACEN_ID: igual que las sucursales, solo se aceptarán los almacenes de dichas sucursales, se pide por parámetro para no hacer una consulta y traer el almacen.
	-P_CAJA_ID: Se asume que solo se pasará alguna Caja 1 de las sucursales permitidas.
	-P_TIPO_DOCTO: O -> Orden de compra, V -> Venta mostrador.
	Retorna:
	-R_DOCTO_PV_ID: El id del documento de punto de venta generado.
	-R_FOLIO: El folio del documento de venta generado.
*/
DECLARE VARIABLE V_FOLIO CHAR(9);
DECLARE VARIABLE V_SERIE VARCHAR(3);
DECLARE VARIABLE V_CONSECUTIVO NUMERIC(9,0);
DECLARE VARIABLE V_FOLIO_RAW VARCHAR(10);
DECLARE VARIABLE V_UNID_COMPROM CHAR(1) = 'N';
BEGIN
	--OBTENEMOS EL CONSUCUTIVO CORRESPONDIENTE SEGUN LA CAJA A LA CUAL SE LE ASIGNARÁ LA VENTA
	SELECT SERIE, CONSECUTIVO
    FROM FOLIOS_CAJAS
    WHERE CAJA_ID = :P_CAJA_ID AND TIPO_DOCTO = :P_TIPO_DOCTO
    INTO :V_SERIE, :V_CONSECUTIVO;
	
	--CONCATENAMOS LA SERIE CON EL CONSECUTIVO
	V_FOLIO_RAW = V_SERIE || V_CONSECUTIVO;
 
	--FORMATEAMOS EL FOLIO A 9 CARACTERES, LLENANDO LOS ESPACIOS FALTANTES CON 0 A LA IZQUIERDA DEL CONSECUTIVO
	EXECUTE PROCEDURE FORMAT_FOLIO_CON_CEROS(:V_FOLIO_RAW)
    RETURNING_VALUES :R_FOLIO;
	
	--SI ES UNA ORDEN DE VENTA, COMPROMETEMOS LAS UNIDADES
	IF(P_TIPO_DOCTO = 'O') THEN
		V_UNID_COMPROM = 'S';
	
	INSERT INTO DOCTOS_PV(
		DOCTO_PV_ID,
		CAJA_ID,
		TIPO_DOCTO,
		SUCURSAL_ID,
		FOLIO,
		FECHA,
		HORA,
		CAJERO_ID,
		CLAVE_CLIENTE,
		CLIENTE_ID,
		ALMACEN_ID,
		MONEDA_ID,
		TIPO_CAMBIO,
		ESTATUS,
		APLICADO,
		SISTEMA_ORIGEN,
		VENDEDOR_ID,
		UNID_COMPROM,
		DESCRIPCION
	) VALUES (
		-1,					--DOCTO_PV_ID
		:P_CAJA_ID,			--CAJA_ID
		:P_TIPO_DOCTO,		--TIPO_DOCTO
		:P_SUCURSAL_ID,		--SUCURSAL_ID
		:R_FOLIO,			--FOLIO
		CURRENT_DATE,		--FECHA
		CURRENT_TIME,		--HORA
		95195954,			--CAJERO_ID
		:P_CLAVE_CLIENTE,	--CLAVE_CLIENTE
		:P_CLIENTE_ID,		--CLIENTE_ID
		:P_ALMACEN_ID,		--ALMACEN_ID
		1,					--MONEDA_ID
		1,					--TIPO_CAMBIO
		'N',				--ESTATUS,
		'N',				--APLICADO
		'PV',				--SISTEMA_ORIGEN
		17703248,			--VENDEDOR_ID/ Es el id del vendedor FYTTSAGO
		:V_UNID_COMPROM,	--UNID_COMPROM
		'VENTA FYTTSAGO'	--DESCRIPCION
	)
	RETURNING DOCTO_PV_ID
	INTO :R_DOCTO_PV_ID;
	
	--ACTUALIZAMOS EL CONSECUTIVO
	UPDATE FOLIOS_CAJAS
	SET CONSECUTIVO = CONSECUTIVO + 1
	WHERE CAJA_ID = :P_CAJA_ID AND TIPO_DOCTO = :P_TIPO_DOCTO;
	
	SUSPEND;
	
	--Por:CYA
END
 
CREATE OR ALTER PROCEDURE VENTA_A_ORDEN_DOCTO_PV(P_DOCTO_PV_ID INTEGER)
RETURNS(
	R_DOCTO_PV_ID                  INTEGER,
  	R_FOLIO                        CHAR(9),
  	R_SOLICITUD_TRASPASO_IN_ID     INTEGER,
  	R_UNIDADES_FALTANTES           NUMERIC(18,5)
)
AS
/*
	PROCEDIMIENTO CREADO PARA FYTTSAGO, CONVIERTE UNA VENTA MOSTRADOR ('V') A UNA ORDEN DE VENTA ('O') SIN APLICAR, ES DECIR SE ASUME QUE
	LA VENTA MOSTRADOR ESTABA EN PROCESO.
	SE COPIA LA CARATULA DEL DOCUMENTO, ASÍ COMO LAS PARTIDAS QUE LLEVABA. FINALMENTE SE BORRA TANTO LOS DETALLES COMO LA CARATULA, SE ASUEM QUE NO TENÍA LIGAS, COBROS NI
	RELACIONES ENTRE SISTEMAS, INVENTARIOS, CXC, ETC.
*/
DECLARE VARIABLE V_CAJA_ID				INTEGER;
DECLARE VARIABLE V_TIPO_DOCTO			CHAR(1);
DECLARE VARIABLE V_SUCURSAL_ID			INTEGER;
DECLARE VARIABLE V_CLAVE_CLIENTE 		VARCHAR(20);
DECLARE VARIABLE V_CLIENTE_ID			INTEGER;
DECLARE VARIABLE V_ALMACEN_ID			INTEGER;
DECLARE VARIABLE V_ORDEN_ID				INTEGER;
DECLARE VARIABLE V_CLAVE_ARTICULO		VARCHAR(20);
DECLARE VARIABLE V_ARTICULO_ID			INTEGER;
DECLARE VARIABLE V_UNIDADES				NUMERIC(18,5);
DECLARE VARIABLE V_PRECIO_UNITARIO		NUMERIC(18,6);
DECLARE VARIABLE V_PRECIO_MODIFICADO	CHAR(1);
DECLARE VARIABLE V_ST_ID                INTEGER;
DECLARE VARIABLE V_FALTANTES            NUMERIC(18,5);
DECLARE VARIABLE V_IGN1                 INTEGER;
DECLARE VARIABLE V_IGN2                 CHAR(9);
BEGIN
	--INICIALIZAMOS RETORNOS
	R_SOLICITUD_TRASPASO_IN_ID = NULL;
  	R_UNIDADES_FALTANTES = 0;
	
	--OBTENEMOS LOS DATOS NECESARIOS DEL DOCUMENTO DE VENTA
	SELECT CAJA_ID, TIPO_DOCTO, SUCURSAL_ID, CLAVE_CLIENTE, CLIENTE_ID, ALMACEN_ID
	FROM DOCTOS_PV
	WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID
	INTO :V_CAJA_ID, :V_TIPO_DOCTO, :V_SUCURSAL_ID, :V_CLAVE_CLIENTE, :V_CLIENTE_ID, :V_ALMACEN_ID;
 
	--CREAMOS LA ORDEN DE VENTA
	SELECT R_DOCTO_PV_ID, R_FOLIO
	FROM CARATULA_DOCTOS_PV_FYTTSAGO(:V_SUCURSAL_ID, :V_ALMACEN_ID, :V_CLAVE_CLIENTE, :V_CLIENTE_ID, :V_CAJA_ID, 'O')
	INTO :R_DOCTO_PV_ID, :R_FOLIO;
	
	--RECORREMOS CADA DETALLE Y LO VAMOS COPIANDO A LA ORDEN DE VENTA
	FOR
		SELECT CLAVE_ARTICULO, ARTICULO_ID, UNIDADES, PRECIO_UNITARIO, PRECIO_MODIFICADO
		FROM DOCTOS_PV_DET
		WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID
		INTO :V_CLAVE_ARTICULO, :V_ARTICULO_ID, :V_UNIDADES, :V_PRECIO_UNITARIO, :V_PRECIO_MODIFICADO
	DO
	BEGIN
		--SI EL PRECIO NO FUE MODIFICADO, NO LE PASAMOS EL PRECIO, LO DEJAMOS NULL
		IF(V_PRECIO_MODIFICADO = 'N') THEN
			V_PRECIO_UNITARIO = NULL;
		--NO SE MANEJARAN LOS ID DE LOS TRASPASOS, PUES EN TEORIA, CUANDO ESTE SP SEA LLAMADO, ES PORQUE SE LLEGÓ A UN ARTICULO SIN EXISTENCIAS QUE NECESITA UN TRASPASO, POR LO QUE
		--SE CAMBIA A UNA ORDEN, ENTONCES TODAS LAS PARTIDAS ANTERIORES (ARTICULOS), DEBERÍAN ESTAR CORRECTOS EN SUS EXISTENCIAS
		EXECUTE PROCEDURE INS_DOCTOS_PV_DET_FYTTSAGO(:R_DOCTO_PV_ID, :V_CLAVE_ARTICULO, :V_ARTICULO_ID, :V_UNIDADES, :V_PRECIO_UNITARIO, :R_SOLICITUD_TRASPASO_IN_ID)
		RETURNING_VALUES :V_ST_ID, :V_FALTANTES, :V_IGN1, :V_IGN2;
		
		--SI SE DEVOLVIÓ UNA SOLICITUD DE TRASPASO, ES DECIR QUE SE GENERÓ UNA SOLICITUD, POR LO QUE LA DEVOLVEMOS
		IF (V_ST_ID IS NOT NULL AND V_ST_ID <> 0) THEN
      		R_SOLICITUD_TRASPASO_IN_ID = V_ST_ID;
		
		IF (V_FALTANTES IS NOT NULL) THEN
      		R_UNIDADES_FALTANTES = R_UNIDADES_FALTANTES + V_FALTANTES;
	END
	
	--FINALMENTE ELIMINAMOS LOS DETALLES Y EL DOCUMENTO DE VENTA
	DELETE FROM DOCTOS_PV_DET
	WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID;
		
	DELETE FROM DOCTOS_PV
	WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID;
	
	--POR: CYA
END
 
 
CREATE OR ALTER PROCEDURE INS_DOCTOS_PV_DET_FYTTSAGO(P_DOCTO_PV_ID INTEGER, P_CLAVE_ARTICULO VARCHAR(20), P_ARTICULO_ID INTEGER, P_UNIDADES NUMERIC(18,5), P_PRECIO_CAPTURADO NUMERIC(18,6), P_SOLICITUD_TRASPASO_ID INTEGER)
RETURNS(
	R_SOLICITUD_TRASPASO_IN_ID	INTEGER,
	R_UNIDADES_FALTANTES		NUMERIC(18,5),
	R_DOCTO_PV_ID_ORDEN			INTEGER,
	R_FOLIO_ORDEN				CHAR(9)
)
AS
/*
	PROCEDIMIENTO CREADO PARA FYTTSAGO, POR LO QUE HAY DECISIONES TOMADAS PARA TALES FINES, LAS CUALES SE COMENTARAN
	PARAMETROS DE ENTRADA
		-P_CLINETE_ID: SI NO SE PROPORCIONA UN PRECIO CAPTURADO, SE NECESITA EL ID DEL CLIENTE PARA CALCULAR EL PRECIO DEL ARTICULO
		-P_PRECIO_CAPTURADO: VALOR OPCIONAL, USADO PARA MODIFICAR EL PRECIO ORGINAL DEL ARTICULO, SE ASUME QUE SE INGRESA SIN IVA, SI ES NULL, SE USARÁ EL PRECIO ORIGINAL
		-P_SOLICITUD_TRASPASO_ID:
			ESTE PARAMETRO ES OPCIONAL, SI ES NULL Y LAS UNIDADES SOLICITADAS NO SE ENCUENTRAN DISPONIBLES EN LA SUCURSAL PERO SI EN OTRA. SE GENERARA UNA SOLICITUD DE TRASPASO
			Y POR MIENTRAS, SE GENERARA UNA VENTA CON LAS UNIDADES DISPONIBLES.
			AHORA, SI SE PASA EL ID DE LA SOLICITUD DE TRASPASO, QUIERE DECIR QUE PARA ESTE DOCUMENTO DE PUNTO DE VENTA, YA A HABIDO OTRA PARTIDA (ARTICULO) CON EXISTENCIAS DISPONIBLES
			INSUFICIENTES Y SE GENERO UNA SOLICITUD, POR TANTO, SI PARA ESTE ARTICULO SE NECESITA HACER UNA SOLICITUD, SE AÑADIRÁ A ESE ID YA EXISTENTE
	RETORNOS
		-R_SOLICITUD_TRASPASO_IN_ID: SI SE GENERA AQUI LA CARATULA DE LA SOLICITUD DE TRASPASO, SE DEVUELVE, EN CASO CONTRARIO SE DEVUELVE 0
		-R_UNIDADES_FALTANTES: SI SE GENERO UNA SOLICITUD O SE AÑADIO A LOS DETALLES DE UNA YA EXISTENTE, TE DEVUELVE LAS UNIDADES FALTANTES DEL ARTICULO LAS CUALES SE INGRESARON A LA SOLICITUD
		-R_DOCTO_PV_ID_ORDEN: SI NO HUBO EXISTENCIAS SUFICIENTES, DEVUELVE EL ID DE LA ORDEN GENERADA
		-R_FOLIO_ORDEN: FOLIO DE LA ORDEN GENERADA		 	
*/
DECLARE VARIABLE V_POSICION 			INTEGER;
DECLARE VARIABLE V_PRECIO_UNITARIO 		NUMERIC(18,6);
DECLARE VARIABLE V_PRECIO_MODIFICADO 	CHAR(1) = 'N';
DECLARE VARIABLE V_EXIS_ACTUAL 			NUMERIC(18,5);
DECLARE VARIABLE V_EXIS_COMPROM 		NUMERIC(18,5);
DECLARE VARIABLE V_EXIS_DISP 			NUMERIC(18,5);
DECLARE VARIABLE V_EXIS_TOTAL 			NUMERIC(18,5);
DECLARE VARIABLE V_UNIDADES_FALTANTES 	NUMERIC(18,5);
DECLARE VARIABLE V_SUCURSAL_ID_SOL 		INTEGER;
DECLARE VARIABLE V_SOLICITUD_TRASPASO_IN_ID INTEGER;
DECLARE VARIABLE V_FOLIO_SOLICITUD 		VARCHAR(9);
DECLARE VARIABLE V_EXIS_LOOP			NUMERIC(18,5);
DECLARE VARIABLE V_SUCURSAL_ID_LOOP		INTEGER;
DECLARE VARIABLE V_PRECIO_TOTAL_NETO 	NUMERIC(18,6);
DECLARE VARIABLE V_TIPO_CLIENTE_ID		INTEGER;
DECLARE VARIABLE V_SUCURSAL_ID			INTEGER;
DECLARE VARIABLE V_ALMACEN_ID			INTEGER;
DECLARE VARIABLE V_CLIENTE_ID			INTEGER;
DECLARE VARIABLE V_CLAVE_CLIENTE 		VARCHAR(20);
DECLARE VARIABLE V_TIPO_DOCTO			CHAR(1);
BEGIN
	
	--INICIALIZAMOS LOS RETORNOS
	R_SOLICITUD_TRASPASO_IN_ID = 0;
	R_UNIDADES_FALTANTES = 0;
	
	--OBTENEMOS LOS DATOS NECESARIO DEL DOCUMENTO DE VENTA
	SELECT TIPO_DOCTO, SUCURSAL_ID, CLIENTE_ID, ALMACEN_ID
	FROM DOCTOS_PV
	WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID
	INTO :V_TIPO_DOCTO, :V_SUCURSAL_ID, :V_CLIENTE_ID, :V_ALMACEN_ID;
	
	--OBTENEMOS LA POSICION DE LA PARTIDA
	SELECT COALESCE(MAX(POSICION), 0) + 1
	FROM DOCTOS_PV_DET
	WHERE DOCTO_PV_ID = :P_DOCTO_PV_ID
	INTO :V_POSICION;
 
	--SI SE CAPTURÓ UN PRECIO MANUAL, ES DECIR NO SE USA EL ORIGINAL DE SISTEMA, SE INDICA QUE EL PRECIO FUE MODIFICADO
	IF(P_PRECIO_CAPTURADO IS NOT NULL) THEN
	BEGIN
		V_PRECIO_UNITARIO = P_PRECIO_CAPTURADO;
		V_PRECIO_MODIFICADO = 'P';
	END
	ELSE
	BEGIN
		--SI NO SE CAPTURÓ PRECIO MANUAL, BUSCAMOS EL PRECIO CORRESPONDIENTE AL TIPO DE CLIENTE QUE ES
		SELECT TIPO_CLIENTE_ID
		FROM CLIENTES
		WHERE CLIENTE_ID = :V_CLIENTE_ID
		INTO :V_TIPO_CLIENTE_ID;
		  
		--SI ES DE TIPO MOSTRADOR O E-COMMERCE USAMOS EL PRECIO LISTA
		IF(V_TIPO_CLIENTE_ID = '3454' OR V_TIPO_CLIENTE_ID = '17703250') THEN
			SELECT PRECIO
		  	FROM PRECIOS_ARTICULOS
			WHERE ARTICULO_ID = :P_ARTICULO_ID AND PRECIO_EMPRESA_ID = 42
			INTO :V_PRECIO_UNITARIO;
		  
		--SI ES DISTRIBUIDOR O FYTTSER USAMOS EL PRECIO DISTRIBUIDOR
		IF(V_TIPO_CLIENTE_ID = '3453' OR V_TIPO_CLIENTE_ID = '94978320') THEN
		  	SELECT PRECIO
		  	FROM PRECIOS_ARTICULOS
			WHERE ARTICULO_ID = :P_ARTICULO_ID AND PRECIO_EMPRESA_ID = 58490
			INTO :V_PRECIO_UNITARIO;
	END
	
	--CALCULAMOS EL PRECIO TOTAL NETO
	V_PRECIO_TOTAL_NETO = ROUND(V_PRECIO_UNITARIO * P_UNIDADES, 2);
	
	--CALCULAMOS LA EXISTENCIA DISPONIBLE
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :V_ALMACEN_ID, :V_SUCURSAL_ID)
	RETURNING_VALUES :V_EXIS_ACTUAL, :V_EXIS_COMPROM, :V_EXIS_DISP;
	
	--SI ES MENOR A LAS UNIDADES SOLICITADAS Y ADEMAS ES UN DOCUMENTO DE TIPO 'V', HABRÁ 2 CASOS, HAY EXISTENCIA EN OTROS ALMACENES O NO HAY
	IF(P_UNIDADES > V_EXIS_DISP) THEN
	BEGIN
		SELECT EXISTENCIA
		FROM GET_EXIS_ART_SUCURSAL(0, :P_ARTICULO_ID)
		INTO :V_EXIS_TOTAL;
		
		--SI LAS UNIDADES TOTALES AÚN NO SON SUFICIENTES, LANZAR UNA EXCEPCION, PUES NO SE PODRÁ HACER LA VENTA
		IF(V_EXIS_TOTAL < P_UNIDADES ) THEN
		BEGIN
			EXCEPTION EX_STOCK_INSUFICIENTE
				'No hay existencia suficiente para el artículo. Disponible: '
			    || CAST(V_EXIS_TOTAL AS VARCHAR(20))
			    || ', solicitado: '
			    || CAST(P_UNIDADES AS VARCHAR(20));
		END
		ELSE
		BEGIN
			--INSERTAMOS LOS DETALLES EN EL DOCUMENTO DE PUNTO DE VENTA SOLO SI HAY AL MENOS 1 UNIDAD DE CUALQUIER MANERA, AUN SI ES VENTA U ORDEN, YA QUE SE ES VENTA IGUALMENTE SE ELIMINARÁ PERO SE COPIARÁ A LA ORDEN
			IF(P_UNIDADES > 0) THEN
				INSERT INTO DOCTOS_PV_DET(
					DOCTO_PV_DET_ID,
					DOCTO_PV_ID,
					CLAVE_ARTICULO,
					ARTICULO_ID,
					UNIDADES,
					PRECIO_UNITARIO,
					PRECIO_UNITARIO_IMPTO,
					PRECIO_TOTAL_NETO,
					PRECIO_MODIFICADO,
					VENDEDOR_ID,
					ROL,
					POSICION
				) VALUES(
					-1,
					:P_DOCTO_PV_ID,
					:P_CLAVE_ARTICULO,
					:P_ARTICULO_ID,
					:P_UNIDADES,
					:V_PRECIO_UNITARIO,
					:V_PRECIO_UNITARIO * 1.16,
					:V_PRECIO_TOTAL_NETO,
					:V_PRECIO_MODIFICADO,
					17703248,
					'N',
					:V_POSICION
				);
		
			--ELIMINAMOS LA VENTA Y LA GENERAMOS LA ORDEN SI ES UNA VENTA
			IF(V_TIPO_DOCTO = 'V') THEN
				EXECUTE PROCEDURE VENTA_A_ORDEN_DOCTO_PV(:P_DOCTO_PV_ID)
				RETURNING_VALUES :R_DOCTO_PV_ID_ORDEN, :R_FOLIO_ORDEN, :R_SOLICITUD_TRASPASO_IN_ID, :R_UNIDADES_FALTANTES;
		
			--SOLO SI ES ORDEN DE VENTA GENERAMOS EL TRASPASO E INSERTAMOS LA PARTIDA DEL ARTICULO
			IF(V_TIPO_DOCTO = 'O') THEN
			BEGIN
				
				--SI LA EXISTENCIA ES NEGATIVA, DEJARLA EN 0
				IF(V_EXIS_DISP < 0) THEN
					V_EXIS_DISP = 0;
				
				--SI ES UNA ORDEN DE VENTA, GENERAMOS EL TRASPASO
				V_UNIDADES_FALTANTES = P_UNIDADES - V_EXIS_DISP;
				
				-- RETORNAMOS LAS UNIDADES FALTANTES
				R_UNIDADES_FALTANTES = V_UNIDADES_FALTANTES;
				
				--SI SE PROPORCIONA UN ID DE LA SOLICITUD DE TRASPASO, A ESA SOLICITUD AGREGAREMOS EL ARTICULO EN LOS DETALLES
				IF(P_SOLICITUD_TRASPASO_ID IS NOT NULL) THEN
				BEGIN
					INSERT INTO SOLICITUDES_TRASPASO_IN_DET(
						SOLICITUD_TRASPASO_IN_DET_ID,
						SOLICITUD_TRASPASO_IN_ID,
						CLAVE_ARTICULO,
						ARTICULO_ID,
						UNIDADES,
						POSICION
					) VALUES(
						-1,
						:P_SOLICITUD_TRASPASO_ID,
						:P_CLAVE_ARTICULO,
						:P_ARTICULO_ID,
						:V_UNIDADES_FALTANTES,
						-1
					);
				END
				ELSE
				BEGIN
					--SI NO SE PROPORCIONA EL ID, SIGNIFICA QUE ES EL PRIMERO, POR LO QUE SE GENERARA LA CARATULA
					
					-- BUSCAMOS LA SUCURSAL DONDE HAY LAS EXISTENCIAS FALTANTES PARA HACER LA SOLICITUD DE TRASPASO
					FOR
						SELECT SUCURSAL_ID, EXISTENCIA
						FROM EXIST_ART_ALM_GEN_SUS(:P_ARTICULO_ID)
						ORDER BY EXISTENCIA
						INTO :V_SUCURSAL_ID_LOOP, :V_EXIS_LOOP
					DO
					BEGIN
						IF(V_EXIS_LOOP >= V_UNIDADES_FALTANTES) THEN
							V_SUCURSAL_ID_SOL = V_SUCURSAL_ID_LOOP;
					END
					
					--SE CREA LA CARATULA DE LA SOLICITUD Y RECUPERAMOS EL ID Y FOLIO DEL MISMO
					SELECT R_SOLICITUD_TRASPASO_IN_ID, R_FOLIO_GENERADO
					FROM CARATURLA_SOLICITUD('SOLICITUD FYTTSAGO', 'SYSDBA', :V_SUCURSAL_ID_SOL, :V_SUCURSAL_ID, :V_ALMACEN_ID)
					INTO :V_SOLICITUD_TRASPASO_IN_ID, :V_FOLIO_SOLICITUD;
					
					--RETORNAMOS EL ID DE LA SOLICITUD SI ES QUE SE CREO
					R_SOLICITUD_TRASPASO_IN_ID = V_SOLICITUD_TRASPASO_IN_ID;
					
					--INSERTAMOS EL DETALLE DEL ARTICULO EN LA SOLICITUD RECIEN CREADA
					INSERT INTO SOLICITUDES_TRASPASO_IN_DET(
						SOLICITUD_TRASPASO_IN_DET_ID,
						SOLICITUD_TRASPASO_IN_ID,
						CLAVE_ARTICULO,
						ARTICULO_ID,
						UNIDADES,
						POSICION
					) VALUES(
						-1,
						:V_SOLICITUD_TRASPASO_IN_ID,
						:P_CLAVE_ARTICULO,
						:P_ARTICULO_ID,
						:V_UNIDADES_FALTANTES,
						-1
					);
				END
			END	
			
		END
	END
	ELSE
	BEGIN
        -- SI HAY EXISTENCIA SUFICIENTE SE INSERTA EL DETALLE
		IF(P_UNIDADES > 0) THEN
			INSERT INTO DOCTOS_PV_DET(
				DOCTO_PV_DET_ID,
				DOCTO_PV_ID,
				CLAVE_ARTICULO,
				ARTICULO_ID,
				UNIDADES,
				PRECIO_UNITARIO,
				PRECIO_UNITARIO_IMPTO,
				PRECIO_TOTAL_NETO,
				PRECIO_MODIFICADO,
				VENDEDOR_ID,
				ROL,
				POSICION
			) VALUES(
				-1,
				:P_DOCTO_PV_ID,
				:P_CLAVE_ARTICULO,
				:P_ARTICULO_ID,
				:P_UNIDADES,
				:V_PRECIO_UNITARIO,
				:V_PRECIO_UNITARIO * 1.16,
				:V_PRECIO_TOTAL_NETO,
				:V_PRECIO_MODIFICADO,
				17703248,
				'N',
				:V_POSICION
			);
	END
	SUSPEND;
	--POR: CYA
END
 
CREATE OR ALTER PROCEDURE INS_DOCTO_PV_COBROS_FYTTSAGO(P_DOCTO_PV_ID INTEGER, P_FORMA_COBRO_ID INTEGER, P_IMPORTE NUMERIC(18,6), P_REFERENCIA VARCHAR(30), P_BANCO VARCHAR(30), P_NUM_TARJETA VARCHAR(4), P_FECHA VARCHAR(30))
AS
/*
	PROCEDIMIENTO CREADO PARA FYTTSAGO, PARA REGISTRAR LOS COBROS DE LAS VENTAS HECHAS, SOLO FUNCIONA PARA METODOS DE PAGO CON TARJETA Y TRANSFERENCIA
	PARAMETROS DE ENTRADA
		-P_FORMA_COBRO_ID: ES EL ID DEL COBRO, SE ASUME QUE SE PASARÁ ALGUNO DE ESTOS 3 ID'S 395563, 395564, 395565
		-P_REFERENCIA: ES LA REFRENCIA ALFANUMERICA DE LA TRANSFERENCIA, PARA LAS TARJETAS ES EL NUMERO DE AUTORIZACION (Num Autorizacion)
		-P_NUM_TARJETA: SON LOS ULTIMOS 4 DIGITOS DE LA TARJETA,
		-P_FECHA: ES UN STRING CON LA FECHA, DE PREFENRENCIA CON EL FORMATO DD/MM/YYY O DD-MM-YYYY, ES OPCIONAL, SOLO NECESARIO SI EL METODO DE PAGO ES CON TRANSFERENCIA (395565)
*/
DECLARE VARIABLE V_FORMA_COBRO_REFER_ID	INTEGER;
DECLARE VARIABLE V_DOCTO_PV_COBRO_ID	INTEGER;
DECLARE VARIABLE V_NOMBRE 				VARCHAR(30);
DECLARE VARIABLE V_VALOR				VARCHAR(30);
BEGIN
	
	--INSERTAMOS EL COBRO
	INSERT INTO DOCTOS_PV_COBROS(
		DOCTO_PV_COBRO_ID,
		DOCTO_PV_ID,
		TIPO,
		FORMA_COBRO_ID,
		IMPORTE,
		TIPO_CAMBIO,
		IMPORTE_MON_DOC
	) VALUES(
		-1,
		:P_DOCTO_PV_ID,
		'C',
		:P_FORMA_COBRO_ID,
		:P_IMPORTE,
		1,
		:P_IMPORTE
	)
	RETURNING DOCTO_PV_COBRO_ID
	INTO :V_DOCTO_PV_COBRO_ID;
	
	--FOR PARA RECORRER CADA REFRENCIA NECESARIA PARA LA FORMA DE COBRO
	FOR
		SELECT FORMA_COBRO_REFER_ID, NOMBRE
		FROM FORMAS_COBRO_REFER
		WHERE FORMA_COBRO_ID = :P_FORMA_COBRO_ID
		INTO :V_FORMA_COBRO_REFER_ID, :V_NOMBRE
	DO
	BEGIN
		IF(V_NOMBRE = 'Num Autorizacion') THEN
			V_VALOR = P_REFERENCIA;
		
		ELSE IF(V_NOMBRE = 'Banco') THEN
			V_VALOR = P_BANCO;
		
		ELSE IF(V_NOMBRE = 'Digitos Tarjeta') THEN
			V_VALOR = P_NUM_TARJETA;
		
		ELSE IF(V_NOMBRE = 'Fecha') THEN
			V_VALOR = P_FECHA;
		
		ELSE IF(V_NOMBRE = 'Num Cuenta') THEN
			V_VALOR = '0000';
		
		ELSE IF(V_NOMBRE = 'Referencia') THEN
			V_VALOR = P_REFERENCIA;
		
		INSERT INTO DOCTOS_PV_COBROS_REFER (
			DOCTO_PV_COBRO_ID,
			FORMA_COBRO_REFER_ID,
			REFERENCIA
		) VALUES(
			:V_DOCTO_PV_COBRO_ID,
			:V_FORMA_COBRO_REFER_ID,
			:V_VALOR
		);
	END
	--POR: CYA
END
 
 
 
CREATE OR ALTER PROCEDURE EXIST_ART_ALM_GEN_SUS (P_ARTICULO_ID INTEGER)
RETURNS (
    SUCURSAL_ID INTEGER,
    ALMACEN_ID INTEGER,
    EXISTENCIA INTEGER,
    COMPROMETIDO INTEGER
)
AS
	--PROCEDIMIENTO QUE DEVUELVE LAS EXISTENCIAS DE UN ARTICULO EN CADA UNA DE LAS SUCURSALES
DECLARE VARIABLE V_DUMMY INTEGER;
BEGIN
	--CEDIS TOTOLCINGO
	ALMACEN_ID = 188104;
	SUCURSAL_ID = 9606947;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	
	--TOTOLCINGO
	ALMACEN_ID = 19;
	SUCURSAL_ID = 384;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	
	--TEPEXPAN
	ALMACEN_ID = 7506737;
	SUCURSAL_ID = 7511208;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	
	--VALLEJO
	ALMACEN_ID = 9604500;
	SUCURSAL_ID = 9604530;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	
	--VIA MORELOS
	ALMACEN_ID = 9603355;
	SUCURSAL_ID = 9605724;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	
	--TEXCOCO
	ALMACEN_ID = 94274615;
	SUCURSAL_ID = 9606894;
	
	EXECUTE PROCEDURE CALC_DISP_ARTALM(:P_ARTICULO_ID, :ALMACEN_ID, :SUCURSAL_ID)
	RETURNING_VALUES :V_DUMMY, :COMPROMETIDO, :EXISTENCIA;
	
	SUSPEND;
	--POR: CYA
END


1ro caratula, 2do detalles x cada articulo, 3 calcular totales 